alias ts='tmux list-session'
alias ta='tmux attach'
alias tat='tmux attach -t $1'
alias lsnum='ls -a1 | wc -l'
alias l='less'
alias vbash='vim ~/.bashrc'
alias sbash='source ~/.bashrc'
alias vconf='vim ~/mxconfig/conf/configuration.yml'
alias vmxc='vim ~/mxconfig/conf/local.yml'

alias ni='node-inspector --web-port=8232'
alias mdb='mocha --debug-brk -t 200000000'

alias sqlplus='rlwrap sqlplus'
alias sqlp='sqlplus dev_ttrela/dev_ttrela@//cluster-b3-20/mastdev'

alias utop='top -u utrelth'
alias psu='ps -u utrelth -f'
alias envs='env | sort'

alias redisc='redis-cli -p 8177'

alias mt='mxstart Engineering'
alias mr='mxrestart Engineering'
alias mp='mxstop Engineering'

alias pd='perl -d'
alias pv='sme && prove'
alias pvv='sme && prove -v'
alias pvr='sme && prove -r'
alias pvvr='sme && prove -rv'
alias pva='sme && prove -r -j40 ~/mastering/MyCT/base/test :: --jobs'
alias pvamyct='sme && prove -r -j40 ~/mastering/MyCT/base/test/MyCT ~/mastering/MyCT/base/test/Mx :: --jobs'
alias pvas='sme && prove -s -r -j1  *.t :: --jobs'
alias pvast='sme && prove --state=save -r -j40  *.t :: --jobs'
alias pvastf='sme && prove --state=failed,save -r -j40 :: --jobs'
alias pvaf='sme && prove --state=failed -r -j40 :: --jobs'
alias gs='git status'
alias gss='git status -s'


alias invm='. ~/.nvm/nvm.sh'
alias nvm10='nvm use 0.10'
alias nvm8='nvm use 0.8'

#alias ll='ls -llhF'
alias ls='ls --color=auto'
alias ll='ls -la'
alias la='ls -alhF'
alias l.='ls -d .* --color=auto'
alias lx='ls -lXB' # Sort by extension
alias lk='ls -lSr' # Sort by size (small to big)
alias lc='ls -ltcr' # Sort by change time (old to new)
alias lu='ls -ltur' # Sort by change time (new to old)
alias lt='ls -ltr' # Sort by date (old to new)

alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .....='cd ../../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias bc='bc -l'
alias sha1='openssl sha1'
alias mkdir='mkdir -pv'
#alias diff='colordiff'
#alias mount='mount |column -t'
alias h='history'
alias j='jobs -l'
alias path='echo -e ${PATH//:/\\n}'
alias now='date +"%T"'
alias nowtime=now
alias nowdate='date +"%d-%m-%Y"'
alias vi=vim
#alias svi='sudo vi'
#alias vis='vim "+set si"'
alias edit='vim'
alias ping='ping -c 5'
alias fastping='ping -c 100 -s.2'
alias ports='netstat -tulanp'
# jalias ipt='sudo /sbin/iptables'
# alias iptlist='sudo /sbin/iptables -L -n -v --line-numbers'
# alias iptlistin='sudo /sbin/iptables -L INPUT -n -v --line-numbers'
# alias iptlistout='sudo /sbin/iptables -L OUTPUT -n -v --line-numbers'
# alias iptlistfw='sudo /sbin/iptables -L FORWORD -n -v --line-numbers'
# alias firewall=iptlist
alias header='curl -I'
alias headerc='curl -I --compress'
alias rm='rm --preserve-root'
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'
# alias apt-get="sudo apt-get"
# alias updatey="sudo apt-get --yes"
# alias update='sudo apt-get upgrade && sudo apt-get update'
#alias update='yum update'
#alias updatey='yum -y update'
# alias root='sudo -i'
# alias su='sudo -i'
# alias reboot='sudo /sbin/reboot'
# alias poweroff='sudo /sbin/poweroff'
# alias halt='sudo /sbin/halt'
# alias shutdown='sudo /sbin/shutdown'
# alias nginxreload='sudo /usr/local/nginx/sbin/nginx -s reload'
# alias nginxtest='sudo /usr/local/nginx/sbin/nginx -t'
# alias lightyload='sudo /etc/init.d/lighttpd reload'
# alias lightytest='sudo /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf -t'
# alias httpdreload='sudo /usr/sbin/apachectl -k graceful'
# alias httpdtest='sudo /usr/sbin/apachectl -t && /usr/sbin/apachectl -t -D DUMP_VHOSTS'
# alias backup='sudo /home/scripts/admin/scripts/backup/wrapper.backup.sh --type local --taget /raid1/backups'
# alias nasbackup='sudo /home/scripts/admin/scripts/backup/wrapper.backup.sh --type nas --target nas01'
# alias s3backup='sudo /home/scripts/admin/scripts/backup/wrapper.backup.sh --type nas --target nas01 --auth /home/scripts/admin/.authdata/amazon.keys'
# alias rsnapshothourly='sudo /home/scripts/admin/scripts/backup/wrapper.rsnapshot.sh --type remote --target nas03 --auth /home/scripts/admin/.authdata/ssh.keys --config /home/scripts/admin/scripts/backup/config/adsl.conf'
# alias rsnapshotdaily='sudo  /home/scripts/admin/scripts/backup/wrapper.rsnapshot.sh --type remote --target nas03 --auth /home/scripts/admin/.authdata/ssh.keys  --config /home/scripts/admin/scripts/backup/config/adsl.conf'
# alias rsnapshotweekly='sudo /home/scripts/admin/scripts/backup/wrapper.rsnapshot.sh --type remote --target nas03 --auth /home/scripts/admin/.authdata/ssh.keys  --config /home/scripts/admin/scripts/backup/config/adsl.conf'
# alias rsnapshotmonthly='sudo /home/scripts/admin/scripts/backup/wrapper.rsnapshot.sh --type remote --target nas03 --auth /home/scripts/admin/.authdata/ssh.keys  --config /home/scripts/admin/scripts/backup/config/adsl.conf'
# alias amazonbackup=s3backup
# alias playavi='mplayer *.avi'
# alias vlc='vlc *.avi'
# alias playwave='for i in *.wav; do mplayer "$i"; done'
# alias playogg='for i in *.ogg; do mplayer "$i"; done'
# alias playmp3='for i in *.mp3; do mplayer "$i"; done'
# alias nplaywave='for i in /nas/multimedia/wave/*.wav; do mplayer "$i"; done'
# alias nplayogg='for i in /nas/multimedia/ogg/*.ogg; do mplayer "$i"; done'
# alias nplaymp3='for i in /nas/multimedia/mp3/*.mp3; do mplayer "$i"; done'
# alias music='mplayer --shuffle *'
# alias dnstop='dnstop -l 5  eth1'
# alias vnstat='vnstat -i eth1'
# alias iftop='iftop -i eth1'
# alias tcpdump='tcpdump -i eth1'
# alias ethtool='ethtool eth1'
# alias iwconfig='iwconfig wlan0'
alias meminfo='free -m -l -t'
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'
# alias cpuinfo='lscpu'
# alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'
# alias rebootlinksys="curl -u 'admin:my-super-password' 'http://192.168.1.2/setup.cgi?todo=reboot'"
# alias reboottomato="ssh admin@192.168.1.1 /sbin/reboot"
alias wget='wget -c'
# alias ff4='/opt/firefox4/firefox'
# alias ff13='/opt/firefox13/firefox'
# alias chrome='/opt/google/chrome/chrome'
# alias opera='/opt/opera/opera'
# alias ff=ff13
# alias browser=chrome 
alias df='df -H'
alias du='du -ch'
# alias top='atop'
# alias nfsrestart='sync && sleep 2 && /etc/init.d/httpd stop && umount netapp2:/exports/http && sleep 2 && mount -o rw,sync,rsize=32768,wsize=32768,intr,hard,proto=tcp,fsc natapp2:/exports /http/var/www/html &&  /etc/init.d/httpd start'
# alias mcdstats='/usr/bin/memcached-tool 10.10.27.11:11211 stats'
# alias mcdshow='/usr/bin/memcached-tool 10.10.27.11:11211 display'
# alias flushmcd='echo "flush_all" | nc 10.10.27.11 11211'
# alias cdndel='/home/scripts/admin/cdn/purge_cdn_cache --profile akamai'
# alias amzcdndel='/home/scripts/admin/cdn/purge_cdn_cache --profile amazon'
# alias cdnmdel='/home/scripts/admin/cdn/purge_cdn_cache --profile akamai --stdin'
# alias amzcdnmdel='/home/scripts/admin/cdn/purge_cdn_cache --profile amazon --stdin'
